# Generated by Django 3.0.5 on 2020-09-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent_model',
            old_name='address',
            new_name='add',
        ),
    ]
